services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      DB_HOST: wkgcga9iwohbo6g20erdtiym
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: nqszdfyMJ6XcjXToyM4sy6o1VrMvm1TLToLiMkUkqWpPfsiLQ1A0ZVsw8sIAnleU